cmake_options: -DENABLE_BUILD_TOOLS=ON
dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes
  ecmwf/eckit
  ecmwf/atlas
dependency_branch: develop
parallelism_factor: 8
