cmake_options: -DENABLE_BUILD_TOOLS=ON
dependency_cmake_options: |
  ecmwf/atlas: "-DENABLE_TESSELATION=ON"
dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  qhull/qhull@refs/tags/v8.0.2
  ecmwf/eccodes
  ecmwf/eckit
  ecmwf/atlas
dependency_branch: develop
parallelism_factor: 8
