cmake_options: -DENABLE_BUILD_TOOLS=ON
dependency_cmake_options: |
  ecmwf/eccodes: "-DENABLE_ECKIT_GEO=ON"
dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.4
  ecmwf/eckit
  ecmwf/eccodes
  ecmwf/atlas
  ecmwf/metkit
dependency_branch: develop
parallelism_factor: 8
