#!/bin/sh


#set -xe
set -e


#export BILINEAR2=1
#export ECREGRID_MARS_AREA=1

#export ECREGRID_DISABLE_LSM=1

export ECREGRID_DEBUG=1

export ECREGRID_EMOS=1

export ECREGRID_WRITE_CHUNKS=1
#export ECREGRID_EMOS_GAUSS=1

export ECREGRID_UNROTATED_AREA=1

#export ECREGRID_SIMPLE_COPY=1


data=../data_in

area1="90.0/-180.0/-90.0/180.0"
area1="90.0/0/-90.0/360"
area1="80.0/-40.0/20.0/60.0"
valgrind=valgrind
valgrind="valgrind --leak-check=full"
valgrind=

TON1=1
ANNA1=1
ANNA=0

TON=0

rm -f fix_it

ll2ll=0.25/0.25
ll2ll=1/1
ll2ll=0.5/0.5
sh2sh=80
area7="60.0/-10.0/10.0/15.0"
area8="60.0/10.0/10.0/35.0"
ggg=200
#===============================================
# WIND
#---------
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/10u10v.grib -o $data/y_10u10v.grib -l 1/1
#./ecregrid -i $data/vortdiv.grib -o $data/y_vortdiv.grib -l 1/1
#./ecregrid -i $data/uv_reduced_gaussian.grib1 -o $data/y_uv_reduced_gaussian.grib -l 0.5/0.5
#./ecregrid -i $data/uv_reduced_gaussian.grib1 -o $data/y_uv_reduced_gaussian.grib -l 0.5/0.5 -r 0/80
./ecregrid -i $data/uv_reduced_gaussian.grib1 -o $data/y_uv_reduced_gaussian.grib -l 0.5/0.5 -m cubic
#./ecregrid -i $data/vortdiv.grib -o $data/y_vortdiv.grib -l 1/1 -r 0/80.0
fi
#===============================================
# RD
#---------
if ( test $TON -eq 1) ; then
#anna
#./ecregrid -i $data/anna.grib -o $data/y_anna-ll.grib -l 1.875/1.89473684210526315789
# miha
#./ecregrid -i $data/MFM_sfc_o3_2009091500+012.grib2 -o $data/y_miha-ll.grib -l 0.1/0.1
# miha 2
#./ecregrid -i $data/CHI_2010031700+000.grib2 -o $data/y_miha-ll.grib -l 0.1/0.1
./ecregrid -i $data/FMI_SFC_2010031700+000.grib2 -o $data/y_miha-ll.grib -l 0.1/0.1 
#./ecregrid -i $data/FMI_SFC_2010031700+000.grib2 -o $data/y_miha-ll.grib -l 0.1/0.1 -v gtopo
fi
#===============================================
# SH to LL
#---------
if ( test $TON1 -eq 1) ; then
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_ll-spectral.grib -t 106
#./ecregrid -i $data/spectral.grib -o $data/y_spectral-ll.grib -g $ggg -e
./ecregrid -i $data/spectral_511.grib1 -o $data/y_spectral-ll.grib -l $ll2ll
# rot
#./ecregrid -i $data/spectral.grib -o $data/y_spectral-ll.grib -l $ll2ll -r -30/10 -a $area7
#./ecregrid -i $data/spectral.grib -o $data/y_spectral-ll.grib -l $ll2ll -r -30/10
#./ecregrid -i $data/spectral.grib -o $data/y_spectral-ll.grib -l $ll2ll -a $area7
#./ecregrid -i $data/spectral.grib -o $data/y_spectral-ll.grib -l 0.5/0.5 -a $area7
fi
#===============================================
# SH to SH
#---------
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/spectral.grib -o $data/y_spectral-spectral.grib -t $sh2sh
sh2sh=399
./ecregrid -i $data/vortdiv.grib -o $data/y_spectral-spectral.grib -t $sh2sh -d
#./ecregrid -i $data/vortdiv.grib -o $data/y_spectral-spectral.grib -t $sh2sh
fi
#===============================================
# LL to LL
#---------


# SURFACE
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l 0.4/0.4 -a $area1 -v 10min

#same as emos
echo ssssssssssssssssssssssssssssssssssssssssss
#./ecregrid -i $data/2t.grib -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v predefined -m bilinear

#mett=linear
mett=cubic
mett=doublelinear
mett=average
mett=averageweighted
mett=nearest
mett=linearfit
mett=bilinear
release=/usr/local/lib/metaps/li./ecregrid/1.2.0/bin
release=/usr/local/lib/metaps/li./ecregrid/1.1.1/bin
release="."

$releas./ecregrid -i $data/2t.grib -o $data/y_2t-latlon.grib -l 0.125/0.125 -v predefined -m $mett
exit
mv $data/y_2t-latlon.grib $data/y-ll.mars.grib
#----------------
#$releas./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v predefined -m bilinear
$releas./ecregrid -i $data/nn.grib -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v predefined -m bilinear -a $area1
mv $data/y_surface_latlon-latlon.grib $data/y_surface_latlon-latlon.grib.sa
#----------------
export ECREGRID_DISABLE_LSM=1
$releas./ecregrid -i $data/2t.grib -o $data/y_2t-latlon.grib -l 0.125/0.125 -v predefined -m $mett
mv $data/y_2t-latlon.grib $data/y-ll.ecregrid.grib
echo zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
#----------------
#$releas./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v predefined -m bilinear
$releas./ecregrid -i $data/nn.grib -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v predefined -m bilinear -a $area1
mv $data/y_surface_latlon-latlon.grib $data/y_surface_latlon-latlon.grib.bez
#----------------
grib_compare $data/y-ll.mars.grib $data/y-ll.ecregrid.grib
grib_compare $data/y_surface_latlon-latlon.grib.sa $data/y_surface_latlon-latlon.grib.bez
echo wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
exit
#----------------
$releas./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v 10min -m bilinear
mv $data/y_surface_latlon-latlon.grib $data/y_surface_latlon-latlon.grib.sa

#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v 10min -m average
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon.grib -l 0.4/0.4 -v 10min -m bilinear

############################################################
# isti nekako
#grib_compare $data/y_surface_latlon-latlon.grib $data/surface_latlon-latlon-mars.grib

#./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/y_surface_surface_gaussian-latlon.grib -l 0.4/0.4 -v 10min -m linearfit
#mv $data/y_surface_surface_gaussian-latlon.grib $data/y-ll.ecregrid.grib
#grib_compare $data/y_surface_surface_gaussian-latlon.grib $data/surface_rg-latlon-mars.grib

#./ecregrid -i $data/nn.grib -o $data/y_surface_latlon-nn-latlon.grib -l 0.4/0.4 -v 10min -m doublelinear
#./ecregrid -i $data/nn.grib -o $data/y_surface_latlon-nn-latlon.grib -l 0.4/0.4 -v 10min -m bilinear
#mv $data/y_surface_latlon-nn-latlon.grib $data/y-ll.ecregrid.grib
#grib_compare $data/y-ll.ecregrid.grib $data/y-ll.mars.grib
############################################################
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll  -v 10min
#./ecregrid -i /vol/marsdev/data/build/linux/ia32/opensuse103/data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll -a $area1 -v 10min

#./ecregrid -i /vol/marsdev/data/build/linux/ia32/opensuse103/data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll -v 10min

#./ll_area.mars $data/surface_latlon.grib1 $data/y_ll $ll2ll $area1
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll -a $area1
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll -a $area1 -v gtopo
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll  -v gtopo

#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll 
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll -a $area1 -v gtopo
#./ecregrid -i $data/surface_latlon.grib1 -v gtopo -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll -a $area1 -v predefined
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_subarea.grib -l $ll2ll
#./ll_area.mars $data/surface_latlon.grib1 $data/y_ll $ll2ll $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon.grib -l $ll2ll -v 10min
#./ll.mars $data/surface_latlon.grib1 $data/y_ll $ll2ll
fi


# UPPER AIR
# same as EMOS
if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_latlon.grib1 -o $data/upper_air_latlon-latlon_subarea.grib -l $ll2ll -a $area1
#./ll_area.mars $data/upper_air_latlon.grib1 $data/yup_ll $ll2ll $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_latlon.grib1 -o $data/upper_air_latlon-latlon.grib -l $ll2ll
#./ll.mars $data/upper_air $data/yup_ll $ll2ll
fi



#===============================================
# G to G
#---------
g2g=80

if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-gaussian.grib  -g $g2g
#./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-gaussian.grib  -g $g2g -v gtopo
#./ll.mars $data/surface_gaussian.grib1 $data/y_g $g2g
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian.grib1 -o $data/y_upper_air_gaussian-gaussian.grib  -g $g2g
#./ll.mars $data/upper_air_gaussian.grib1 $data/yup_g $g2g
fi


#===============================================
# G to LL
#---------
g2ll="0.5/0.5"
g2ll="1/1"
pole="0.0/80.0"

if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-latlon_subarea.grib  -l $g2ll -a $area1
#./ll_area.mars $data/surface_gaussian.grib1 $data/y_g-ll $g2ll $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-latlon.grib  -l $g2ll
#./ll.mars $data/surface_gaussian.grib1 $data/y_g-ll $g2ll
fi


# small differencies on the poles only => against EMOS
if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian.grib1 -o $data/y_upper_air_gaussian-latlon.grib  -l $g2ll -m average
#./ll.mars $data/upper_air_gaussian.grib1 $data/yup_g-ll $g2ll
fi


#===============================================
# FRAME
#---------
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-gaussian_frame.grib -f 2
./ecregrid -i $data/surface_gaussian.grib1 -o ccc -f 2
fi


####
if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_frame.grib -a $area1 -l 2/2 -f 3
fi

#===============================================
# BITMAP
#---------
if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-latlon_bitmap.grib -l 2/2 -b ~mas/zavod/bitmap/ecm_001.bitmap
fi


#===============================================
# Force REGULAR and REDUCED
#---------
if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-gaussian_reduced.grib -e
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/y_surface_gaussian_reduced-gaussian.grib -u
fi


#===============================================
# Read list => lat lon value
if ( test $TON -eq 1) ; then
$valgrind ./ecregrid -i $data/upper_air_gaussian.txt -x ascii -o $data/y_upper_air_txt_gaussian-latlon_subarea.grib  -l $g2ll -a $area1
fi

if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian.txt -x ascii -o $data/y_upper_air_txt_gaussian-latlon_subarea_linear.grib  -l $g2ll -a $area1 -m linear
fi
#---------



#===============================================
# Read from binary data
if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian.dat -x binary -g 200  -o $data/y_upper_air_dat_gaussian-latlon_subarea.grib  -l $g2ll -a $area1
fi


#===============================================
# To List of points ascii
#---------
#export DISABLE_LSM=1
if ( test $TON -eq 1) ; then
./ecregrid -i $data/field2.grib2 -o y_field2-list_bilinear.txt  -w latlon_miha.txt -m bilinear
fi


#===============================================
# ROTATION
#---------
#binary
if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-latlon_subarea_rotation_bilinear.dat -r $pole  -l $g2ll -a $area1 -m bilinear -x binary
fi



if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-latlon_subarea_rotation_bilinear.grib -r $pole -l $g2ll -a $area1 -m bilinear
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian.grib1 -o $data/y_surface_gaussian-latlon_subarea_rotation.grib -r $pole  -l $g2ll -a $area1
#./llrot.mars _$data/surface_gaussian.grib1 $data/y_g-llrot $g2ll $area1 $pole
fi


# Exactly the same as EMOS
if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian.grib1 -o $data/y_upper_air_gaussian-latlon_subarea_rotation.grib -r $pole  -l $g2ll -a $area1
#./llrot.mars $data/upper_air_gaussian.grib1 $data/yup_g-llrot $g2ll $area1 $pole
fi


rg2ll="1/1"
#===============================================
# RLL to LL
#---------
area11="82.0/-10.0/0.0/20.0"

if ( test $TON -eq 1) ; then
#./ecregrid -i $data/surface_latlon_reduced.grib1 -o $data/y_surface_latlon_reduced-latlon_subarea.grib  -l $rg2ll -a $area11
./ecregrid -i $data/surface_latlon_reduced.grib1 -o $data/y_surface_latlon_reduced-latlon_subarea.grib  -l $rg2ll  -r 0/80.0
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_latlon_reduced.grib1 -o $data/y_surface_latlon_reduced-latlon.grib  -l $rg2ll
fi


#===============================================
# RG to LL
#---------
rg2ll="1/1"
#rg2ll="1.15/1.15"

if ( test $TON -eq 1) ; then
#valgrind ./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/y_surface_gaussian_reduced-latlon_subarea.grib  -l $rg2ll -a $area1 -v 10min
#valgrind ./ecregrid -i $data/in_johanes.grib -o $data/johanes.grib -l 0.25/0.25 -a 75/-30/30/45
#valgrind ./ecregrid -i $data/in_johanes2.grib -o $data/johanes2.grib -l 0.25/0.25 -a 75/-30/30/45
#valgrind ./ecregrid -i /scratch/rd/naj/INPUT_finm_20100414_133_Z_12000.grib -o $data/johanes.grib -l 0.25/0.25 -a 75/-30/30/45
#./ecregrid -i /scratch/rd/naj/INPUT_finm_20100414_133_Z_12000.grib -o $data/johanes.grib -l 0.25/0.25 -a 75/-30/30/45
valgrind ./ecregrid -i /scratch/rd/naj/INPUT_finm_20100414_133_Z_12000.grib -o $data/johanes.grib -l 0.25/0.25  -a 75/-30/30/45
#miha
#./ecregrid -i /scratch/mo/mod/public/sinisa/RIU_2011051800+000.grib2 -o $data/miha.grib -l 0.25/0.25
#./ll_area.mars $data/surface_gaussian_reduced.grib1 $data/y_rg-ll $rg2ll $area1
fi



if ( test $TON -eq 1) ; then
#./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/y_surface_gaussian_reduced-latlon.grib  -l $rg2ll -v 10min
./ecregrid -i /vol/marsdev/data/build/linux/ia32/opensuse103/data/upper_air_gaussian_reduced.grib1 -o proba.grib -l 0.4/0.4 -m linearfit
grib_compare -f -b generatingProcessIdentifier,indicatorOfTypeOfLevel,level,yearOfCentury,month,day proba.grib /vol/marsdev/data/build/linux/ia32/opensuse103/data/upper_air_gaussian_reduced.grib1-latlon.grib.two
#./ll.mars $data/surface_gaussian_reduced.grib1 $data/y_rg-ll $rg2ll
fi


#SF
rg2ll="0.5/0.5"
rg2ll="0.2/0.2"
rg2ll="0.4/0.4"
if ( test $TON -eq 1) ; then
#export ECREGRID_CHECK_CONSERVING=1
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-latlon.grib  -l $rg2ll
#./ll.mars $data/upper_air_gaussian_reduced.grib1 $data/yup_rg-ll $rg2ll 
fi


#ROTATION
if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/y_surface_gaussian_reduced-latlon_subarea_rotation_bilinear.grib -r $pole -l $rg2ll -a $area1 -m bilinear
#./llrot.mars $data/surface_gaussian_reduced.grib1 $data/y_rg-llrot $rg2ll $area1 $pole
fi


# isti
if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-latlon_subarea_rotation.grib -r $pole -l $rg2ll -a $area1
#./llrot.mars $data/upper_air_gaussian_reduced.grib1 $data/yup_rg-llrot $rg2ll $area1 $pole
fi



#===============================================
# RG to G
#---------
rg2g=200

if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/y_surface_gaussian_reduced-gaussian_subarea.grib -g $rg2g -a $area1
#./g_area.mars $data/surface_gaussian_reduced.grib1 $data/y_rg-g $rg2g $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-gaussian_subarea.grib -g $rg2g -a $area1
#./g_area.mars $data/upper_air_gaussian_reduced.grib1 $data/yup_rg-g $rg2g $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-gaussian.grib -g $rg2g
#./g.mars $data/upper_air_gaussian_reduced.grib1 $data/yup_rg-g $rg2g
fi


#===============================================
# LL to G
#---------
ll2g=80
if ( test $TON -eq 1) ; then
./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-gaussian_subarea.grib -g $ll2g -a $area1
#./g_area.mars $data/surface_latlon.grib1 $data/y_ll-g $ll2g $area1
fi


if ( test $TON -eq 1) ; then
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_subarea.grib -g $ll2g -a $area1
#./ecregrid -i $data/ocean.grib -o $data/ocean-g.grib -g $ll2g
./ecregrid -i $data/ocean.grib -o $data/ocean-g.grib -l 0.25/0.25
#./ecregrid -i /scratch/rd/ne9/glorys/in.grb -o id.grib -l 0.25/0.25
#./ecregrid -i $data/ocean.grib -o $data/ocean-g.grib -l 0.5/0.5

#./g_area.mars $data/upper_air $data/yup_ll-g $ll2g $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian.grib -g $ll2g
#./g.mars $data/upper_air $data/yup_ll-g $ll2g
fi


#===============================================
# RG to RG
#---------
g2g=256
g2g=80
g2g=320
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/surface_gaussian_reduced.grib1 -o $data/surface_gaussian_reduced-gaussian_reduced_subarea.grib -g $g2g -a $area1 -e
./ecregrid -i $data/2t.grib -o 2t_ecregrid.grib -g $g2g -y -m linearfit
#./rg_area.mars $data/surface_gaussian_reduced.grib1 $data/y_rg $g2g $area1
fi


g2g=200
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-gaussian_reduced_subarea.grib -g $g2g -a $area1 -y
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-gaussian_reduced_subarea.grib -g $g2g -y
#./rg_area.mars $data/upper_air_gaussian_reduced.grib1 $data/yup_rg $g2g $area1
fi


if ( test $TON -eq 1) ; then
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o $data/y_upper_air_gaussian_reduced-gaussian_reduced.grib -g $g2g -y
#./rg.mars $data/upper_air_gaussian_reduced.grib1 $data/yup_rg $g2g
fi


#===============================================
# LL to RG
#---------
g2g=200
g2g=80
g2g=400
if ( test $TON -eq 1) ; then
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-gaussian_reduced_subarea.grib -g $g2g -a $area1 -y
./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-gaussian_reduced.grib -g $g2g -y -v 10min
#./ecregrid -i $data/surface_latlon.grib1 -o $data/y_surface_latlon-gaussian_reduced_subarea.grib -g $g2g
fi


if ( test $TON -eq 1) ; then
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced_subarea.grib -g $g2g -a $area1 -y
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced_subarea.grib -g $g2g -y -m averageweighted
export ECREGRID_CHECK_CONSERVING=1
./ecregrid -i $data/high_res.grib -o $data/weighted_out.grib -g $g2g -y -m averageweighted
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced_subarea.grib -g $g2g -y -m average
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced.grib -g $g2g -y
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced_subarea.grib -g $g2g -y
#./ecregrid -i $data/upper_air_latlon.grib1 -o bbb.grib -g $g2g  -y -j slope -m cubic
fi

# GLOBAL

if ( test $TON -eq 1) ; then
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced.grib -g $g2g -y
#./ecregrid -i $data/upper_air_latlon.grib1 -o $data/y_upper_air_latlon-gaussian_reduced.grib  -y
#./ecregrid -i /scratch/ma/mas/lakes.grb -o $data/lakes_rg.grib  -y -g 320
#./ecregrid -i $data/geir.grb -o $data/geir_rg.grib  -y -g 320
#./ecregrid -i $data/lsmoro_T159 -o $data/lsmoro_T159_256  -y -g 256
#./ecregrid -i $data/lsmoro_T159 -o zzz  -y -g 256 -j stddev
#./ecregrid -i $data/lsmoro_T159 -o $data/lsmoro_T159_256  -y -g 256 -j slope
#./ecregrid -i $data/lsmoro_T159 -o uuu  -y -g 256 -j slope -m cubic
#./ecregrid -i $data/lsmoro_T159 -o uuu  -y -g 256 -j anisotropy -m cubic
#./ecregrid -i $data/lsmoro_T159 -o uuu  -y -g 256 -m cubic 
#./ecregrid -i $data/lsmoro_T159 -o uuu  -y -g 256 -m averageweighted 
export ECREGRID_CHECK_CONSERVING=1
./ecregrid -i $data/upper_air_gaussian_reduced.grib1 -o uuu  -y -g 256 -m averageweighted 
export ECREGRID_CELL_CENTER=1
#./ecregrid -i /scratch/ma/mas/gc_1km.grb -o uuu  -y -g 256 -m averageweighted 
#./ecregrid -i /scratch/ma/mas/gc_1km.grb  -o lsm.grb -y -g 160 -y 1 -q 12
#./ecregrid -i /scratch/ma/mas/gc_1km.grb  -o lsm.grb -y -g 256
#./ecregrid -i /scratch/ma/mas/gc_1km.grb  -o lsm.grb -y -g 160
#./ecregrid -i /scratch/ma/mas/diffs  -o vvvvv -m cubic -y -g 48 -j slope
#./ecregrid -i /scratch/ma/mas/diffs  -o vvvvv -m cubic -y -g 48 -j orientation
#./ecregrid -i $data/lsmoro_T159 -o uuu  -y -g 256 -j orientation -m cubic
#./ecregrid -i $data/lsm.grib -o $data/lsm256.grib  -y -g 256
#./ecregrid -i $data/lsm.grib -o $data/lsm.5.5.grib -l 0.5/0.5
#./ecregrid -i $data/geir.grb -o $data/geir_rg.grib  -y -g 320 -a 90/0/-90/360
#./ecregrid -i $data/geir.grb -o $data/geir_rg_from_ll.grib  -g 320 -y
#./ecregrid -i $data/geir.grb -o $data/geir_ll.grib  -l 1/1
#./ecregrid -i $data/geir.grb -o $data/geir_ll.grib  -l 0.2666/0.2666
fi


#===============================================

